version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_project_sql
      MYSQL_USER: zem
      MYSQL_PASSWORD: zem
